FROM mcr.microsoft.com/dotnet/sdk:10.0.101

WORKDIR /app

COPY README.md ./README.md
COPY LICENSE.txt ./LICENSE.txt

COPY src/MyTestApplication/ ./src/MyTestApplication
COPY src/ReGenSource ./src/ReGenSource

RUN chmod +x src/MyTestApplication/build_with_local_nuget.sh
RUN ./src/MyTestApplication/build_with_local_nuget.sh
